- name: Install cfssl and cfssljson
  get_url:
    url: https://pkg.cfssl.org/R1.2/cfssl_linux-amd64
    dest: /usr/local/bin/cfssl
    mode: 0755

- name: Install cfssl and cfssljson
  get_url:
    url: https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64
    dest: /usr/local/bin/cfssljson
    mode: 0755

- name: Copy ca-cert config files
  copy:
    src: certs/
    dest: /etc/kubernetes/pki/etcd/
    owner: root
    group: root
    directory_mode : true

- name: Generate CA certs 
  shell: |
    cd /etc/kubernetes/pki/etcd
    cfssl gencert -initca ca-csr.json | cfssljson -bare ca -
  args:
    executable: /bin/bash

- name: Generate etcd client certs
  shell: |
    cd /etc/kubernetes/pki/etcd
    cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=client client.json | cfssljson -bare client
  args:
    executable: /bin/bash