- name: Generate SSH keys
  shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
  args:
    creates: /root/.ssh/id_rsa
- name: copy-ssh-key-id
  shell: |
    cat /root/.ssh/id_rsa.pub | ssh -o "StrictHostKeyChecking no" -i ~/.ssh/csi-aws-west-2.pem centos@ec2-18-236-83-228.us-west-2.compute.amazonaws.com "mkdir -p ~/.ssh && chmod 700 ~/.ssh && cat >>  ~/.ssh/authorized_keys"
