- name: copy-ssh-key-id
  shell: |
    mkdir -p .ssh

- name: Sending private key to severs
  copy:
    src: _ssh/id_rsa
    dest: /root/.ssh/id_rsa
    owner: root
    group: root
    mode: 0644

- name: Sending public key to severs
  copy:
    src: _ssh/id_rsa.pub
    dest: /root/.ssh/id_rsa.pub
    owner: root
    group: root
    mode: 0644

- name: Adding common private key to authorized_keys
  shell: |
    cat /root.ssh/id_rsa.pub >> authorized_keys