- name: copy-ssh-key-id
  shell: |
    mkdir -p .ssh

- name: Sending private key to severs
  copy:
    src: ../_ssh/id_rsa
    dest: /root/.ssh/id_rsa
    owner: root
    group: root
    mode: 0400

- name: Sending public key to severs
  copy:
    src: ../_ssh/id_rsa.pub
    dest: /root/.ssh/id_rsa.pub
    owner: root
    group: root
    mode: 0400

- name: Adding common private key to authorized_keys
  shell: |
    cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
    cat /root/.ssh/id_rsa.pub >> /home/centos/.ssh/authorized_keys
