- name: install docker dependencies
  become: yes
  yum:
    name: "{{item}}"
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - policycoreutils-python

- name: Install container-selinux rpm from a remote repo
  yum:
    name: docker-ce-17.06.0.ce-1.el7.centos.x86_64
    state: present

- name: Install container-selinux rpm from a remote repo
  yum:
    name: docker-ce-selinux-17.06.0.ce-1.el7.centos.noarch
    state: present

# can be needed in some systems
#  - name: Enable extra repos
#    command: subscription-manager repos --enable=rhel-7-server-extras-rpms

- name: Add docker-ce repo
  command: yum-config-manager  --add-repo https://download.docker.com/linux/centos/docker-ce.repo


- name: Installs docker
  yum: 
    name: docker-ce # docker in some distros
    state: installed     

- name: restart docker
  systemd: 
    name: docker 
    state: started # restarted, If restarted on already existing machines (master & worker node), the machines cannot be accessed with ssh. If you stopped docker, machine must be stop & boot again.   
    daemon_reload: yes
    enabled: yes
